const fs = require('fs');
const path = require('path');

const DIST = path.join(__dirname, '..', 'dist');
const ROOT = path.join(__dirname, '..');

// Directories to copy
const COPY_DIRS = ['css', 'js', 'icons'];
const COPY_FILES = ['index.html', 'manifest.json', 'service-worker.js'];

function copyDirSync(src, dest) {
  fs.mkdirSync(dest, { recursive: true });
  for (const entry of fs.readdirSync(src, { withFileTypes: true })) {
    const srcPath = path.join(src, entry.name);
    const destPath = path.join(dest, entry.name);
    if (entry.isDirectory()) {
      copyDirSync(srcPath, destPath);
    } else {
      fs.copyFileSync(srcPath, destPath);
    }
  }
}

console.log('🏗️  Building LifeOS for mobile...');

// Clean & create dist
if (fs.existsSync(DIST)) {
  fs.rmSync(DIST, { recursive: true });
}
fs.mkdirSync(DIST, { recursive: true });

// Copy directories
for (const dir of COPY_DIRS) {
  const src = path.join(ROOT, dir);
  if (fs.existsSync(src)) {
    copyDirSync(src, path.join(DIST, dir));
    console.log(`  ✅ Copied ${dir}/`);
  }
}

// Copy files
for (const file of COPY_FILES) {
  const src = path.join(ROOT, file);
  if (fs.existsSync(src)) {
    fs.copyFileSync(src, path.join(DIST, file));
    console.log(`  ✅ Copied ${file}`);
  }
}

// Create API config
const API_URL = process.env.LIFEOS_API_URL || '';
const configContent = `// Auto-generated by build-mobile.js\nwindow.LIFEOS_API_URL = '${API_URL}';\n`;
fs.writeFileSync(path.join(DIST, 'js', 'config.js'), configContent);
console.log('  ✅ Created js/config.js');

// Inject config.js into index.html (before other scripts)
let html = fs.readFileSync(path.join(DIST, 'index.html'), 'utf8');
if (!html.includes('config.js')) {
  html = html.replace('<script', '<script src="js/config.js"></script>\n    <script');
  fs.writeFileSync(path.join(DIST, 'index.html'), html);
  console.log('  ✅ Injected config.js into index.html');
}

console.log('\n🎉 Mobile build complete! Run `npx cap sync` to update native projects.');
